Web and OpenAPI howto
vertx-howtos/web-and-openapi-howto pull request #1
Opened 2019-02-28 17:18 UTC by slinkydeveloper

I preferred to write the how to updated for vertx 3.7 (for the new error handling strategy), so the vertx version is of course 3.7 (I tested it with local snapshot installs)

2019-03-02 10:40 UTC, jponge requested changes
Great start, just make sure you use Asciidoc includes to make sure the docs remain sync'ed with the code.

2019-03-02 10:40 UTC, jponge commented on README.adoc
> +[source,java]
You should include code snippets using Asciidoc `include`, possibly with tags so you don't include the whole file but smaller bits.

2019-03-03 11:28 UTC, slinkydeveloper commented
When I import all the verticle I cannot find any way to hide callouts. The only thing I find is: https://github.com/asciidoctor/asciidoctor/issues/2961 . Maybe we can add an `hide-callout` rule inside vertx howto theme?

2019-03-04 08:03 UTC, jponge commented
Then just don't import all the verticle and show tag by tag :-)

You can always link to the full file.

2019-03-04 21:06 UTC, jponge commented
@slinkydeveloper Could you add a _"See also"_ section? I think right now you don't have a how-to to cross-link with, but you can definitely link to the relevant pieces of documentation 😉

2019-03-05 15:38 UTC, jponge approved these changes
Just need some Gradle ;-)

2019-03-06 16:25 UTC, jponge approved these changes

2019-03-12 20:13 UTC, jponge commented
@slinkydeveloper go for a merge?

2019-03-13 09:51 UTC, slinkydeveloper commented
Can we wait for 3.7?

2019-03-13 12:19 UTC, jponge commented
We can, but how-tos are still WIP so you could safely merge as well.

Le mer. 13 mars 2019 à 10:51, Francesco Guardiani <notifications@github.com>
a écrit :

> Can we wait for 3.7?
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/vertx-howtos/web-and-openapi-howto/pull/1#issuecomment-472352737>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AABlaYyhmAYuyggmmLf9BrlqGLCjy9Y7ks5vWModgaJpZM4bXUqa>
> .
>

2019-03-13 14:32 UTC, merged